name: 'Dependabot SHA Comment Action'
description: 'Update the version comment next to a sha hash from a dependabot update.'
inputs: 
  GITHUB_TOKEN:
    description: 'Github token of the repository'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'